# Build documentation of ReadTheDocs

name: Document on ReadTheDocs
# TODO: Check running criteria for script
on:
  push:
    branches:
      - dev

jobs:
  document:
    name: Documentation build on ReadTheDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Retrieve package version
        run: |
          VERSION_STR=$(grep -m 1 VERSION setup.py)
          VERSION_STR=${VERSION_STR//[ \']/}
          echo "$VERSION_STR" >> $GITHUB_ENV
        shell: bash

      - name: Trigger documentation build
        run: |
          RESPONSE=$(curl -X POST --header \
          "Authorization: Token $TOKEN" https://readthedocs.org/api/v3/projects/$PROJECT/versions/latest/builds/)
          echo "RESPONSE=$RESPONSE" >> $GITHUB_ENV
        env:
          PROJECT: 'loyverse'
          TOKEN: ${{ secrets.readthedocs_token }}

      - name: Check curl response
        run: |
          echo $RESPONSE
