# Publish package to TestPyPi

name: Build and publish package to TestPyPi
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build and publish to TestPyPi
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install required packages
        run: python3 -m pip install --user --upgrade wheel

      - name: Build distributions
        run: python3 setup.py sdist bdist_wheel

      - name: Publish to TestPyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.testpypi_token }}
          repository_url: https://test.pypi.org/legacy/
